on:
  push:
    branches:
      - master
name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      with: # shimataro/ssh-key-actionに渡すパラメーター
        private-key: ${{ secrets.SSH_KEY }} # 必須
        known-hosts: ${{ secrets.KNOWN_HOSTS }} # 省略可
    - name: run deploy script
      env:
        port: ${{ secrets.PORT }}
        host: ${{ secrets.HOST }}
        owner:  ${{ secrets.OWNER }}
      run:
        #ssh -i ~/.ssh/id_rsa ${owner}@${host} "cd /home/${owner}/conoha && git pull origin master && sudo systemctl restart disbotc"
        ssh -i ~/.ssh/id_rsa ${owner}@${host} "cd /home/${owner}/games && git pull origin master && sudo python3 version_up.py"
